apiVersion: v1
kind: Service
metadata:
  name: app1-sample-loadbalancer-service
  labels:
    app: app1-sample
spec:
  type: ClusterIP
  selector:
    app: app1-sample
  ports:
    - port: 80
      targetPort: 80
