apiVersion: v1
kind: Secret
metadata:
  name: storage-secret
type: Opaque
data:
  azurestorageaccountname: dHJhaW5pbmdjb250YWluZXIwMQ==
  azurestorageaccountkey: dXVVSEd2WGNEbjZxaFV1RVNvTGpGMkszK0FqeFppOEpOY3R0U2F4bGJDNXRzWVhwSEZXZ3VJK204UFBzYzRBRzVWc1krT1JXWHFSTitBU3RsOXRzc3c9PQ==
