apiVersion: v1
kind: Secret
metadata:
  name: storage-secret
type: Opaque
data:
  azurestorageaccountname: bXVsdGljb250YWluZXIwMQ==
  azurestorageaccountkey: ZzdEWW1sWFIzZHI0ekRCNWVjRVA3bm94eHVUcVlTQ0dTTXRzWFhiNkx1WmpidjZLNkRnRmNkWnRjRStyOEpsSktqTHdZZ0hqcDFQRitBU3RQNDRNZnc9PQ==
