apiVersion: v1
kind: Service
metadata:
  name: app4-sample-loadbalancer-service
  labels:
    app: app4-sample
spec:
  type: LoadBalancer
  selector:
    app: app4-sample
  ports:
    - port: 80
      targetPort: 80
