apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sample-app2
  labels:
    app: sample-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app2
  template:
    metadata:
      labels:
        app: sample-app2
    spec:
      containers:
      - name: sample-app2
        image: ajayy6796/training
        ports:
        - containerPort: 80
