apiVersion: v1
kind: Service
metadata:
  name: app2-sample-loadbalancer-service
  labels:
    app: sample-app2
spec:
  type: LoadBalancer
  selector:
    app: sample-app2
  ports:
    - port: 80
      targetPort: 80
